# Generated by Django 4.2.4 on 2023-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('story_time', models.DateTimeField()),
                ('story_id', models.BigIntegerField(unique=True)),
                ('story_link', models.TextField(null=True)),
                ('tag_list', models.TextField(null=True)),
            ],
        ),
    ]
