# Generated by Django 3.1.2 on 2023-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='testing_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
