# Generated by Django 4.2.4 on 2023-09-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='story_time',
            field=models.TextField(),
        ),
    ]
