# Generated by Django 3.1.2 on 2023-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_storymodel_testing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymodel',
            name='media_path',
            field=models.TextField(blank=True),
        ),
    ]
